server {
    listen 7860;
    client_max_body_size 0;
    access_log off;

    # ttyd Web 终端（/term/）
    location = /term { return 301 /term/; }

    location /term/ {
        proxy_pass         http://127.0.0.1:7862/;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade    $http_upgrade;
        proxy_set_header   Connection $http_connection;
        proxy_set_header   Host       $host;
        proxy_read_timeout 86400s;
    }

    # OpenClaw 主界面（所有其他请求）
    location / {
        proxy_pass         http://127.0.0.1:7861;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade    $http_upgrade;
        proxy_set_header   Connection $http_connection;
        proxy_set_header   Host       $host;
        proxy_read_timeout 86400s;
    }
}
